# Use a valid Python base image
FROM python:3.13.0

# Set the working directory
WORKDIR /application

# Copy only requirements first (for Docker caching)
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the project
COPY . .

# Expose Flask port
EXPOSE 5000

# Set environment variable for Flask app entrypoint
ENV FLASK_APP=application.py

# Run flask server
CMD ["flask", "run", "--host=0.0.0.0"]
